---
title: "Class 7 Functions and Packages"
author: "Kathreeni"
date: "1/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##Funtions revisiited
Load (i.e. **source**) our rescale() function from last lecture
```{r}
source("http://tinyurl.com/rescale-R")
```
Test this function 

```{r}
rescale(1:5)
```
```{r}
rescale( c(1:5, "string"))
```

We want to make this function more robust to these types of errors 
```{r}
rescale2(c(1:5, "string"))
```
```{r}
is.numeric(1:5)
```

```{r}
is.numeric(c(1:5, "string"))
```
```{r}
# Lets define an example x and y
x <- c( 1, 2, NA, 3, NA)
y <- c(NA,3,NA,3, 4)
```


```{r}
is.na(x)
```

```{r}
is.na(y)
is.na(x)
is.na(x) & is.na(y)

#summing how many true values
sum(is.na(x) & is.na(y))

#identifying which column holds both logicals true
which(is.na(x) & is.na(y))
```
Now take our working snippet and make a first function
```{r}
both_na <- function(x,y){
    ##Check for NA elements in both input vectors
    sum(is.na(x) & is.na(y))
}
```

```{r}
both_na(x,y)
```

```{r}
x <-  c(NA, NA, NA)
y1 <- c( 1, NA, NA)
y2 <- c( 1, NA, NA, NA)
y3 <- c( 1, NA, NA, NA, NA)
```

```{r}
both_na(x, y3)
```

```{r}
both_na3 <- function(x, y) {
  if (length(x) != length(y)) {
      stop("Input x and y should be vectors of the same length")
}
  na.in.both <- (is.na(x) & is.na(y))
  na.number  <- sum(na.in.both)
  na.which   <- which(na.in.both)
  message("Found ", na.number, " NA's at position(s):",
          paste(na.which, collapse = ", ") )
  return( list(number = na.number, which = na.which) )
}

```